# Site settings
title: Open Source Catholic
email: webmaster@opensourcecatholic.com
description: >
  Helping Catholic developers and organizations involved in software and web
  development find effective solutions for spreading the Gospel of Jesus Christ.
baseurl: ""
url: "http://www.opensourcecatholic.com"
twitter_username: oscatholic
github_username:  opensourcecatholic
permalink: /:year/:title

# Build settings
markdown: kramdown
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

# Gems
gems:
  - jekyll-redirect-from
