# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Source Catholic
email: webmaster@opensourcecatholic.com
description: >
  We want to help Catholic developers and organizations involved in software and
  web development find effective solutions for spreading the Gospel of Jesus
  Christ.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.opensourcecatholic.com" # the base hostname & protocol for your site
twitter_username: oscatholic
github_username:  opensourcecatholic
permalink: /:year/:title.html

# Build settings
markdown: kramdown
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

# Gems
gems:
  - jekyll-redirect-from
